added documentation for preview
USC-InfoLab/w4h-documentation pull request #1
Opened 2024-10-20 02:25 UTC by riyadesale9

2024-10-20 16:57 UTC, lnocera requested changes

2024-10-20 16:57 UTC, lnocera commented on docs/getting-started/preview.md
> +**Dashboard** : An intuitive interface that offers data input forms and visual analytics tools.
Just say what it is not stuff that ChatGPT suggests!

Look at the ICDE demo video/paper (Samrit knows ask in Slack). You want to write something like this:

- Streamlit dashboard featuring:
    - Import data
    - ...  
- Database supporting GeoMTS
- Notebooks:
    - Compliance notebooks in pandas/PySpark

2024-10-20 16:57 UTC, lnocera commented on docs/getting-started/preview.md
> +This document is for the preview of W4H toolkit. W4H Toolkit is an ecosystem that covers most of the common features needed when using wearables in a clinical study or or trial. As studies can have v
This is about the container. Just say what it is and how to get it.

# W4H Toolkit Preview

This is a preview of the Wearables for Health (W4H) Toolkit. To run the preview:
- Get Docker...
- Install...

Then explain what it contains with links to the dashboard, notebooks, database etc.

2024-10-20 16:57 UTC, lnocera commented on docs/getting-started/preview.md
> +# W4H-Preview
Move this all thing in the main README.md Then explain at the end that the rest of documentation is work in progress.

2024-10-20 16:57 UTC, lnocera commented on docs/getting-started/preview.md
> +## Accessing the Dashboard
all this is very good but we just want a top-level list with each item basic information, links, what it does like for the dashboard link to home allows to do x, link to import allows to do y, ... again this should be in the demo and paper.

2024-10-27 18:19 UTC, riyadesale9 commented
Please let me know if I should include information about the following:
1. Detailed steps to install Docker for Linux, MacOS & Windows
2. StreamSim & python APIs like pyGarminAPI, pyFitbitAPI, pyAppleWatchAP 
3. Details about what the notebooks do

2024-10-28 16:29 UTC, lnocera approved these changes

2026-05-01 18:19 UTC, closed without merging

2026-05-01 18:19 UTC, lnocera commented
Obsolete